# -*- coding: utf-8 -*-
"""imageProcessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p1tx7cQpyYCNC0pdkD7AASNJ0wyK4Ju2
"""

import urllib.request

# Download the image 
def downloadImage(url,output_file='test.jpg'):
    request = urllib.request.urlretrieve(url,output_file)





