# -*- coding: utf-8 -*-
"""predictor_setup.ipynb

Ideal use on Colaboratory.

Download the pretrained model for face alignment to local directory and decompress it.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zfj49Sf751eu8tTNiI7nT5DF27Cxn2Mq
"""


import urllib.request
import bz2,shutil
import os

urllib.request.urlretrieve("https://github.com/davisking/dlib-models/raw/master/shape_predictor_68_face_landmarks.dat.bz2", filename="shape_predictor_68_face_landmarks.dat.bz2")
with bz2.BZ2File("shape_predictor_68_face_landmarks.dat.bz2") as fr, open("shape_predictor_68_face_landmarks.dat","wb") as fw:
    shutil.copyfileobj(fr,fw)
if os.path.exists("shape_predictor_68_face_landmarks.dat.bz2"):
  os.remove("shape_predictor_68_face_landmarks.dat.bz2")
else:
  print("The file does not exist")

