# -*- coding: utf-8 -*-
"""predictor_setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zfj49Sf751eu8tTNiI7nT5DF27Cxn2Mq
"""

import urllib.request
urllib.request.urlretrieve("https://github.com/davisking/dlib-models/raw/master/shape_predictor_68_face_landmarks.dat.bz2", filename="shape_predictor_68_face_landmarks.dat.bz2")

import bz2,shutil

with bz2.BZ2File("shape_predictor_68_face_landmarks.dat.bz2") as fr, open("shape_predictor_68_face_landmarks.dat","wb") as fw:
    shutil.copyfileobj(fr,fw)

# import dlib

# predictor_path = 'shape_predictor_68_face_landmarks.dat'
# detector = dlib.get_frontal_face_detector() 
# predictor = dlib.shape_predictor(predictor_path)



